### ISSUE TITLE
Activation of folding rules

### ISSUE THREAD

**Issue by FALLAI-Denis** [zokugun/vscode-cobol-folding#1]
Hi,

It seems that installing the vscode-cobol-folding extension is not enough to enable folding on COBOL sources.

It is also necessary to configure the other parameters at the level of the language mode `[cobol]` concerning the folding at the level of the settings.json (workspace or user).

at least:

```
"[cobol]": {
  "editor.folding": true,
  "editor.foldingStrategy": "auto",
  "editor.showFoldingControls": "always"
  }
```
optional:

```
"[cobol]": {
  "editor.foldingHighlight": true
  }
```

Is this something that can be supported by the extension or does it have to be done in addition to installing the extension?

Thanks.

**Comment by daiyam** [comment]
Yes, it's possible.

**Comment by FALLAI-Denis** [comment]
Hi @daiyam,

In fact, I never tested the "vscode-cobol-foding" extension because I had declared my COBOL rules at the settings.json level for the "explicit folding" extension.

I removed my COBOL rules and activated the "vscode-cobol-folding" extension ... and I have no more folding!

Did I miss something ? A setting to activate or a configuration to make in settings.json?

**Comment by daiyam** [comment]
Yep, there is a bug! I was testing with my default "*" rule. Without it, the extension doesn't work correctly. I'm fixing it.

**Comment by FALLAI-Denis** [comment]
errare humanum est ;-)

**Comment by daiyam** [comment]
I've updated the main extension "Explicit Folding" to fix the issue. It should be fine now.

**Comment by FALLAI-Denis** [comment]
Yes, now it's ok.

I remove all "[cobol]" rules in settings.json and folding is effective on "cobol" source.

With reference to the initial request concerning the foding settings, a priori none is required for the vscode-cobol-folding extension works as expected.

```
  // Spécifique langage "cobol"
  "[cobol]": {
    "files.autoGuessEncoding": true,
    "editor.rulers": [0,{"column":6,"color":"#603020"},7,11,{"column":72,"color": "#603020"},{"column": 80,"color": "#ff0000"}]
  },
```

Thanks for the responsiveness.
